import { app, BrowserWindow, ipcMain } from 'electron';
import started from 'electron-squirrel-startup';
import { registerIpcHandlers } from './ipc';
import { isUpdateCurrentlyUnblocked } from './services/closeGuard';

// Magic constants generated by Forge's Webpack plugin: they tell the app where the
// Webpack-bundled renderer and preload live (dev vs production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (started) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    width: 1024,
    height: 720,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // In dev, open DevTools detached so they don't eat into the app's content area (the window
  // then looks identical in dev and prod). Never in a packaged build.
  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  // Guard against an accidental quit while updates are unblocked — that would leave the
  // game open to a Steam update the next time it's launched.
  let isCloseConfirmed = false;

  // We register this inside createWindow so it can access isCloseConfirmed and mainWindow.
  // Use removeHandler first to prevent multiple registrations on app reactivate.
  ipcMain.removeHandler('confirmQuit');
  ipcMain.handle('confirmQuit', () => {
    isCloseConfirmed = true;
    mainWindow.close();
  });

  mainWindow.on('close', event => {
    if (isCloseConfirmed || !isUpdateCurrentlyUnblocked()) return;

    event.preventDefault();

    // Focus the window if it's minimized or hidden so the user sees the warning
    if (mainWindow.isMinimized()) mainWindow.restore();

    mainWindow.focus();

    // Ask the renderer to show the custom React modal
    mainWindow.webContents.send('request-quit-confirm');
  });
};

// Register the main-process side of the preload bridge before any window loads.
registerIpcHandlers();

app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
