import { app, BrowserWindow, dialog, ipcMain } from 'electron';
import isSquirrelStartup from 'electron-squirrel-startup';
import path from 'path';
import { registerIpcHandlers } from './ipc';
import { logToFile } from './logger';
import { isUpdateCurrentlyUnblocked } from './services/closeGuard';
import { createWindowState } from './windowState';

// Magic constants generated by Forge's Webpack plugin: they tell the app where the
// Webpack-bundled renderer and preload live (dev vs production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (isSquirrelStartup) {
  app.quit();
}

// Our listener overrides Node's default termination, so exit ourselves — resuming after an
// uncaught exception is unsafe (undefined state; this app writes .acf files). Log, notify, exit.
function handleFatalError(scope: string, error: unknown): void {
  logToFile(scope, error instanceof Error ? (error.stack ?? error.message) : String(error));
  dialog.showErrorBox(
    'Steam Update Freezer crashed',
    `A fatal error (${scope}) occurred and the app must close. Details were written to the log.`,
  );
  app.exit(1);
}

process.on('uncaughtException', error => handleFatalError('uncaughtException', error));

// A rejected promise is less catastrophic than an uncaught exception — it needn't corrupt
// synchronous state — so log it for diagnosis but keep running instead of quitting.
process.on('unhandledRejection', reason => {
  logToFile(
    'unhandledRejection',
    reason instanceof Error ? (reason.stack ?? reason.message) : String(reason),
  );
});

const createWindow = (): void => {
  const windowState = createWindowState(1024, 720);

  const mainWindow = new BrowserWindow({
    x: windowState.x,
    y: windowState.y,
    width: windowState.width,
    height: windowState.height,
    minWidth: 400,
    minHeight: 600,
    useContentSize: true,
    icon: path.join(app.getAppPath(), 'assets', 'favicon.ico'),
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  windowState.manage(mainWindow);

  // The whole renderer process died (OOM/native crash) — React and the ErrorBoundary are gone,
  // so record it from main. 'clean-exit' is a normal teardown, not a crash.
  mainWindow.webContents.on('render-process-gone', (_event, details) => {
    if (details.reason === 'clean-exit') return;

    logToFile('render-process-gone', `reason=${details.reason} exitCode=${details.exitCode}`);
  });

  // Hide the default menu in production, but keep it in dev for useful hotkeys (Reload, etc.)
  if (app.isPackaged) {
    mainWindow.setMenu(null);
  }

  mainWindow.setMenu(null);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // In dev, open DevTools detached so they don't eat into the app's content area (the window
  // then looks identical in dev and prod). Never in a packaged build.
  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  // Guard against an accidental quit while updates are unblocked — that would leave the
  // game open to a Steam update the next time it's launched.
  let isCloseConfirmed = false;

  // We register this inside createWindow so it can access isCloseConfirmed and mainWindow.
  // Use removeHandler first to prevent multiple registrations on app reactivate.
  ipcMain.removeHandler('confirmQuit');
  ipcMain.handle('confirmQuit', () => {
    isCloseConfirmed = true;
    mainWindow.close();
  });

  mainWindow.on('close', event => {
    if (isCloseConfirmed || !isUpdateCurrentlyUnblocked()) return;

    event.preventDefault();

    // Focus the window if it's minimized or hidden so the user sees the warning
    if (mainWindow.isMinimized()) mainWindow.restore();

    mainWindow.focus();

    // Ask the renderer to show the custom React modal
    mainWindow.webContents.send('request-quit-confirm');
  });
};

// Register the main-process side of the preload bridge before any window loads.
registerIpcHandlers();

app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
